# Generated by Django 3.1.3 on 2021-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210119_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='src/media/users/2021/01/19/Без_названия.jpeg', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
