# Generated by Django 3.1.3 on 2021-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210120_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('BEL', 'BEL'), ('RUS', 'RUS')], max_length=100, null=True),
        ),
    ]
