# Generated by Django 3.1.3 on 2021-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20210120_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('BELARUS', 'BEL'), ('RUSSIA', 'RUS'), ('UKRAINE', 'UK'), ('POLAND', 'PL'), ('LITHUANIA', 'LT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('european_gender', 'european_gender')], max_length=50, null=True),
        ),
    ]
